---
author: Aram Soylemez
title: "Bellabeat Case Study"
output: html_document
date: now
---

## Ask

It can be said that the one of the main trends in smart devices covers their usage for health, activity tracking. As these trends starting to become mainstream all companies are adjusting their marketing strategies accordingly. And as a tech company aiming a specific market, Bellabeat customers can thoroughly benefit from this sorts of devices. As

Bellabeat wants to gain more insight on the use of health and activity tracking smart devices so that they can widen their perspective on the issue and therefore apply the insights gain into their own devices.

The data is available through Mobius, downloaded from Kaggle. It consists the data of 30 users daily activity. It includes information about daily activity, steps, and heart rate that can be used to explore users’ habits.

## Prepare

I have downloaded the data to my local computer and created a GitHub repo so that I can keep the workflow backed up. 
